<a href="https://colab.research.google.com/github/Lucasgarciaamorim/Borges/blob/master/tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Import TensorFlow
import tensorflow as tf
print(tf.__version__)


2.17.0


In [ ]:
#Create Tensor with tf.constant
scalar = tf.constant(1)
scalar

In [ ]:
#check the number of dimensions of a tensor(ndim stands for number of dimensions)
scalar.ndim


In [ ]:
#Creat a vector
vector = tf.constant([10,10])
vector

In [ ]:
# Check the dimension of our vector
vector.ndim

In [ ]:
# Create a matrix (hax more than 1 dimension)

matrix = tf.constant([[10,7],
                      [7,10]])
matrix

In [ ]:
matrix.ndim

In [ ]:
# Create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]], dtype=tf.float16) #specify the data type with dtype parameter
another_matrix

In [ ]:
# What's the number dimension of the another_matrix?
another_matrix.ndim

In [ ]:
# Let's create a tensor

tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])

tensor


In [ ]:
tensor.ndim

In [ ]:

#What we've created so far:

# * Scalar: a single number
# * Vector: a number with direction (e.g. wind speed and direction)
# * Matrix: a 2-dimensional array of numbers
# * Tensor: an n-dimensional array of numbers

### Creatin tensors with `tf.Variable`


In [ ]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7]) # same thing as declare a variable, i can change after declare
unchangeable_tensor = tf.constant([10,7]) # same thing as declare a constant, i can't change after declare
changeable_tensor, unchangeable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try change one of the elements in our changeable tensor
changeable_tensor[0].assign(7)# to change a tensor created with Variable i use .assign("new value")
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Let's try change our unchangable tensor
unchangeable_tensor[0].assign(7) # i can't change a tensor create with a constant
unchangeable_tensor

## Creating random tensors

Random tensors are tensors of some

In [7]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

# Are they equal?
random_1, random_2, random_1 == random_2



(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)